apiVersion: apps/v1
kind: Deployment
metadata:
  name: valhalla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: valhalla
  template:
    metadata:
      labels:
        app: valhalla
    spec:
      containers:
      - name: valhalla
        image: mapupjpmapupassesment.azurecr.io/valhalla:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - containerPort: 8002
